type: php
build:
    flavor: symfony

web:
    document_root: "/web"
    passthru: "/app_dev.php"

mounts:
    "/app/cache": "shared:files/cache"
    "/app/logs": "shared:files/logs"

hooks:
    build: "./app/console cache:warmup"
